version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "FastapiHunty"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15gh3kbrxwibt"
s3_prefix = "FastapiHunty"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
